project:
  type: website

website:
  title: "IS428VABITeam"
  navbar:
    left:
      - href: project proposal.qmd
        text: Project Proposal
      - href : project_overview.qmd
        text : Project Overview
      - href : data_preparation.qmd
        text : Data Preparation
      - href: storyboard.qmd
        text: Storyboard
      - href : analysis.qmd
        text: Analysis & Results
        menu:
          - text: Question 1
            file: question1_analysis.qmd
          - text: Question 2
            file: question2_analysis.qmd
          - text: Question 3
            file: question3_analysis.qmd
      - href: poster.qmd
        text: Poster
      
          
      # - href: index.qmd
      #  text: Home
      # - href: about.qmd
      #  text: About
      # - href: overview.qmd
      #  text: Overview
      # - href: prototypes.qmd
      #  text: Prototypes
     
      # - href: userguide.qmd
      #  text: User Guide
    right:
      - icon: github
        href: https://github.com/raellusionz/IS428VABITeam
        text: GitHub
  page-footer:
    left: "© 2026 IS428 VABITeam"
    right: "Built with [Quarto](https://quarto.org)"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full
    max-width: 1400px
