project:
  type: website

website:
  title: "IS428VABITeam3"
  navbar:
    left:
      - href : project_overview.qmd
        text : Project Overview
      - href: project proposal.qmd
        text: Project Proposal
      - href : data_preparation.qmd
        text : Data Preparation
      - href: storyboard.qmd
        text: Storyboard
      - href : analysis.qmd
        menu:
          - text: Question 1
            file: question1_analysis.qmd
          - text: Question 2
            file: question2_analysis.qmd
          - text: Question 3
            file: question3_analysis.qmd
      - href: poster.qmd
        text: Poster
      - href: userguide.qmd
        text: User Guide
      
          
      # - href: index.qmd
      #  text: Home

    right:
      - icon: github
        href: https://github.com/raellusionz/IS428VABITeam
        text: GitHub
      - text: Tableau Dashboard
        href : https://public.tableau.com/app/profile/dycia.chin/viz/G2T3TableauWorkbook/Story1
  page-footer:
    left: "© 2026 IS428 VABI Team 3"
    right: "Built with [Quarto](https://quarto.org)"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full
 
